<a href="https://colab.research.google.com/github/TanushreeNayak/FDS_Programs/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
import numpy as np
arr = np.array((4,5,6,7))
print(arr)

[4 5 6 7]


In [ ]:
a = np.array([45,77,85,12])
b = np.array([6,55,85,96])

print("a1 : ",a)
print("a2 : ",b)

print("a > b")
print("a >= b")
print("b < a")
print("b <= a")

print(np.greater(a,b))
print(np.greater_equal(a,b))
print(np.less(b,a))
print(np.less_equal(b,a))

a1 :  [45 77 85 12]
a2 :  [ 6 55 85 96]
a > b
a >= b
b < a
b <= a
[ True  True False False]
[ True  True  True False]
[ True  True False False]
[ True  True  True False]


In [ ]:
values = np.array([1,7,13,105])
print(values.size)
print(values.dtype)
print(values.itemsize * values.size)

4
int64
32


In [ ]:
collab = np.arange(30,71)
print(collab)

collab = np.arange(30,71,2)
print(collab)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
array = [45,52,96,66,32,35,46]

even_numbers = [num for num in array if num % 2 == 0 and 30 <= num <= 70]
print("The even numbers between 30 to 70 are:", even_numbers)

The even numbers between 30 to 70 are: [52, 66, 32, 46]


In [ ]:
import numpy as np

a = np.arange(10,22).reshape((3,4))
print("Original array : ")
print(a)
print("Each element of the array is: ")
for x in np.nditer(a):
  print(x,end=',')

Original array : 
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is: 
10,11,12,13,14,15,16,17,18,19,20,21,

In [ ]:
import numpy as np
import pandas as pd

data = np.array([['',"Col1","Col2"],
                 ["Row1",1,2],
                 ["Row2",3,4]])
print(pd.DataFrame(data=data[1:,1:],index = data[1:,0],columns = data[0,1:]))

     Col1 Col2
Row1    1    2
Row2    3    4


In [ ]:
import numpy as np
import pandas as pd

data = np.array([['',"Col1","Col2"],
                 ["Row1",1,2],
                 ["Row2",3,4]])
print(pd.DataFrame(data=data[1:,1:]))

   0  1
0  1  2
1  3  4


In [ ]:
values = np.array([1,7,13])
print(values.itemsize)

8
